### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by gorkemerdogann** [onury/docma#10]
Hello, I've created doc files with sample js file. There is an error in browser console.(index.html)

Error:

`docma-web.js:38 Uncaught TypeError: Cannot read property 'split' of null
    at Function.t.fromID (docma-web.js:38)
    at window.onload (docma-web.js:38)
`

**Comment by onury** [comment]
Can you provide a sample project and your docma configuration?

**Comment by gorkemerdogann** [comment]
My config:

```json
{
  "src": "./src/MyClass.js",
  "dest": "./docs",
  "app": {
    "title": "My Documentation",
    "routing": "path"
  },
  "template": {
    "path": "default"
  }
}
```

My sample js:

```javascript
/**
 * This is MyClass.
 * @example
 * let myClass = new MyClass();
 */
export default class MyClass {
  
   /**
   * this is a constructor description.
   * @param {number} a this is first number.
   * @param {number} b this is second number.
   * return {Object} an instance
   */ 
  constructor(a, b) {
	  this.a = a;
	  this.b = b;
  }
  
  /**
   * @param {number} a - this is a value.
   * @param {number} b - this is b value.
   * @return {number} result of the numbers.
   */
  sum(a, b){
    return this.a + this.b;
  }
  
}
```

Console error:

```javascript
Uncaught TypeError: Cannot read property 'split' of null
    at Function.t.fromID (docma-web.js:38)
    at window.onload (docma-web.js:38)
```

**Comment by onury** [comment]
The reason is that your config does not set `app.entrance` and Docma had no default value for it. With the new release **v1.4.0** it now defaults to `"api"`. Pls update to the latest.

### Additional Notes:
If you `export` your class in the same line with `class` definition (as in your example), you should explicitly document the name and type. Example:
```js
/**
 * This is MyClass.
 * @class MyClass
 * @example
 * let myClass = new MyClass();
 */
export default class MyClass { }
```
Otherwise, `export default class SomeClass { .. }` will document as `module.exports`.

I suggest, you export your class on a separate line:
```js
/**
 * This is MyClass.
 * @example
 * let myClass = new MyClass();
 */
class MyClass { }

/**
 * @private
 */
export default MyClass;
```

Also, see [build configuration docs](http://onury.github.io/docma/?api=docma#Docma~BuildConfiguration) for how to ignore symbols like `module` and for other useful configurations.

Finally, your constructor's documentation has a typo. `return` should be `@return` or `@returns`.

**Comment by gorkemerdogann** [comment]
Thank you so much for helping. Sorry for my bad. I was looking a lot of documentation tool and I did a mistake.

Best regards, have a nice day!

**Comment by onury** [comment]
No problem at all. Glad to help.
