### ISSUE TITLE
Cannot generate any API files: null contentPath

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#25]
I tried to clone this repository, and simply ran `npm install && npm run docs` in order to generate the documentation.
It first failed because the file ./doc/HOME.md doesn't exist:

> ENOENT: no such file or directory, open '/Volumes/HDD2/Docs/Dev/docma/doc/HOME.md'

After fixing it by simply replacing it by `./README.md` in `docma.config.json` which exists, the docs are generated, but the content path is **null** for every `api` file:

```
Configured SPA Routes:

type     name             path                   contentPath
-------  ---------------  ---------------------  ----------------------
api      _def_            /?api                  null
api      docma            /?api=docma            null
api      docma-web        /?api=docma-web        null
api      docma-web-utils  /?api=docma-web-utils  null
content  changelog        /?content=changelog    content/changelog.html
content  md-test          /?content=md-test      content/md-test.html
content  guide            /?content=guide        content/guide.html
````

What's wrong?

I tried to create a very simple config file and I am having the same problem.

**Comment by onury** [comment]
I generate docs for Docma itself, from code and files in `/doc/`. That directory is [not included in commits](https://github.com/onury/docma/blob/master/.gitignore#L4). So that's normal but I'll remove it from tests though.

> content path is **null** for every `api` file

That's normal and expected. For markdown files, an `html` (content) file is generated, hence the content path.  But for `api` routes (which are generated from `.js` files); don't generate content files. 

The jsdoc output from code files; is assigned to the `docma` object in the web application — so they're dynamically parsed into `dust` templates.

Maybe it should show `Not Applicable` instead of `null`...

**Comment by onury** [comment]
Now, Docma v2 outputs the route table like this:

<img width="862" alt="docma-console-1" src="https://user-images.githubusercontent.com/3665990/38704359-bae19236-3eae-11e8-8da0-2d084156a3ad.png">
