### ISSUE TITLE
@link by namepath

### ISSUE THREAD

**Issue by MaienM** [onury/docma#48]
According to the docs of [`@link`](http://usejsdoc.org/tags-inline-link.html), it should be possible to create link using the namepath. However, when I do so in docma, this creates an incorrect link. Looking at the code, there are some commented out blocks that seem to relate to this, but these appear to be unfinished (`if (symbolNames && symbolNames.indexOf(link) >= 0) {..}` in `Utils.parseLinks` in `DocmaWeb.Utils.js`).

I can work around this by manually prefixing the namepath with `#`, as the namepaths seem to be anchors, but it would be nice to have proper support for this.

**Comment by onury** [comment]
So is the example below a similar case?
`{@link MyClass|see this}` » outputs » `<a href="MyClass">see this</a>`

If so, that is the correct behavior.  

For example, what about `{@link instance.net}`? Is this a code/symbol link? or a website? 
If it's the latter and Docma prepended a `#` by default, the link would be invalid if this is a website link.

Since Docma generates a SPA, a "name path" essentially would be;
- a bookmark on the same page (e.g. `#MyClass`) 
- an internal link to a SPA route (e.g. `?api=MyClass` or `/api/MyClass`)
- or a bookmark on another route (e.g. `?api=code#MyClass` or `/api/code#MyClass`)
So it's the user's responsibility to provide the correct link.

Hope this makes sense.

---
_About the definition you referred to_: This is one of the "wrong" parts about JSDoc. It should have been only a spec and a tool to parse docs from code — not about templating. That definition is actually more about the default HTML output generated by JSDoc (the tool). It generates `{@link MyClass}` to `<a href="MyClass.html">MyClass</a>`. MyClass.**html** would not fit into a SPA like what Docma generates.

**Comment by MaienM** [comment]
Like you said, the URL can be different depending on how docma (or any other JSDoc template) generates the docs: anchors, separate files, etc. I feel that this shouldn't matter when writing the docs, as this is really just an implementation detail of the chosen template. The docs just refer to another object by namepath, it's up to the template to convert this to an URL that it understands. It doesn't make any sense to me to make this the user's responsibility.

I don't understand what you mean when you say this part of the spec is about templating. The spec doesn't lay down any rules about _what_ the generated URL should look like (be it an anchor or another html page), as long as it refers to the object with the given namepath.

With regards to your example of an ambiguous name,  I think the best option would be to consider things that aren't known namepaths to be URLs. This allows the greatest flexibility:

- For a namepath, `@link namespace.Class`.
- For a relative URL, `@link ./path/to/some/file.html`
- For an absolute URL, `@link https://instance.net`

The only possible problem with this is if you have namepaths that shadow relative URLs. Practically speaking, docma will usually generate links starting with `content/` or `?content`, so it should be very easy to avoid these. Additionally, starting the relative URL with `./` makes this very unlikely.

**Comment by onury** [comment]
> I don't understand what you mean when you say this part of the spec is about templating.

I made a general statement about JSDoc not being a proper spec (It actually is not, really) and mixing  specification with implementation. e.g. from JSDoc docs; _"By default, {@link} generates standard HTML anchor tags."_, or _"Forces the link's text to use a monospace font"_ Or the example of `MyClass` to `MyClass.html`. These are/should be implementation details.

Anyway, I see what you mean. We could do some checks to determine whether to parse it as a internal doc link. i.e. if no slashes it'd be a docma link and according to the routing method configured, create the link.. I think this would resolve it.

**Comment by MaienM** [comment]
Ah, I see what you mean. It does contain some stuff that is implementation specific, yeah. I've always just taken these to be examples of the reference implementation rather than part of the spec itself, but they aren't always clearly indicated as such, unfortunately.

**Comment by onury** [comment]
Released with [Docma v3.0.0](https://onury.io/docma/changelog).
